name: Code Quality Check

on: [pull_request]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run ShellCheck
        id: shellcheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
        continue-on-error: true  

      - name: Comment PR
        if: failure()  
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'ShellCheck analysis found issues. Please review the comments.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}